---
vagrant_local:
  vm:
    name: oxideshop
    hostname: oxideshop.dev
    aliases:
      - www.oxideshop.dev
    app_shared_folder:
      source: oxideshop
      target: /var/www/oxideshop
server:
  packages:
    - git
apache:
  docroot: "{{ eshop_path.source }}"
  servername: "{{ vagrant_local.vm.aliases.0 }}"
mysql:
  root_password: oxid
  database: oxid
  user: oxid
  password: oxid
php:
  zendguard:
    install: false
  packages:
    - php5.6-cli
    - php5.6-intl
    - php5.6-mcrypt
    - php5.6-mysql
    - php5.6-gd
    - php5.6-curl
    - php5.6-xml
    - php5.6-bcmath
    - php5.6-mbstring
    - php5.6-soap
  composer:
    prestissimo:
      install: true
mailhog:
  install: true
adminer:
  install: true
adminer_editor:
  install: true
varnish:
  default_config:
    source: "{{ eshop_path.library }}/ReverseProxy/Varnish/default.vcl"
    target: /etc/varnish/default.vcl
  servers_config:
    source: "{{ eshop_path.library }}/ReverseProxy/Varnish/servers_conf.vcl.varnish_4.dist"
    target: /etc/varnish/servers_conf.vcl
selenium:
  install: false
  package:
    firefox:
      deb_url: https://github.com/OXID-eSales/oxvm_assets/raw/master/firefox-mozilla-build_31.0-0ubuntu1_amd64.deb
      deb_checksum: sha256:41c3a02d304a26e10c237516c773ba51d93eb2b11e5a82292bb47b26bb2ba859
    self:
      jar_url: https://github.com/OXID-eSales/oxvm_assets/raw/master/selenium-server-standalone-2.47.1.jar
      jar_checksum: sha256:45665f3bb4dffb668981258faff91823db4a1f6250fd24fd6698ec159a4aeb8a
eshop_path:
  root: "{{ eshop_target_path }}"
  source: "{{ eshop_target_path }}/source"
  tests: "{{ eshop_target_path }}/tests"
  library: "{{ eshop_target_path }}/library"
  modules: "{{ eshop_target_path }}/source/modules"
eshop_target_path: "{{ vagrant_local.vm.app_shared_folder.target }}"
eshop:
  config:
    utf_mode: 1
    use_ssl: false
  composer:
    clean_vendors: true
    env: "SHOP_PATH=\"'{{ eshop_path.source }}'\" SHOP_TESTS_PATH='{{ eshop_path.tests }}' PARTIAL_MODULE_PATHS='null'"
    root: "{{ eshop_path.root }}"
    vendor: "{{ eshop_target_path }}/vendor"
    cache_url: ~
    json_source_url: https://raw.githubusercontent.com/OXID-eSales/oxideshop_ce/b-5.2-ce/source/composer.json
    lock_source_url: https://raw.githubusercontent.com/OXID-eSales/oxideshop_ce/b-5.2-ce/source/composer.lock
    prefer: dist
  source:
    repo: https://github.com/OXID-eSales/oxideshop_ce.git
    version: v6.0.0-rc.1
  sdk:
    path: ~/eshop_sdk
    module_skeleton_generator:
      install: true
      repo: https://github.com/OXID-eSales/module_skeleton_generator.git
    module_certification_tools:
      install: true
      repo: https://github.com/OXID-eSales/module_certification_tools.git
